version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sierra6-unbound-dns_server_1
      APP_PORT: 5334

  server:
    image: ghcr.io/willitmod/axebench-release:v3.0.2-r1@sha256:bbd179793fed078717223f8a9906445fe08cceaa98c34248fc61ef5983cf6c61
    restart: on-failure
    stop_grace_period: 30s
    init: true
    environment:
      AXE_HOST: 0.0.0.0
      AXE_PORT: 5334
      HOME: /ui
    volumes:
      - ${APP_DATA_DIR}/ui:/ui

  unbound:
    image: mvance/unbound:latest
    restart: unless-stopped
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ${APP_DATA_DIR}/unbound:/opt/unbound/etc/unbound