version: "3.7"

services:
  unbound:
    image: mvance/unbound:latest
    restart: unless-stopped
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"

  ui:
    build: ./ui
    restart: unless-stopped
    ports:
      - "8080:8080"