version: "3.7"

services:
  unbound:
    image: mvance/unbound:latest
    restart: unless-stopped
    ports:
      - "5335:53/udp"
      - "5335:53/tcp"
    volumes:
      - ${APP_DATA_DIR}/unbound:/opt/unbound/etc/unbound

  app_proxy:
    environment:
      APP_HOST: sierra6-unbound-dns_web_1
      APP_PORT: 80

  web:
    image: nginx:alpine
    restart: unless-stopped